DROP DATABASE IF EXISTS checkout;

CREATE DATABASE checkout;

USE checkout;

DROP TABLE if EXISTS CUSTOMER_DATA;


CREATE TABLE CUSTOMER_DATA ( 
    ID INT NOT NULL AUTO_INCREMENT,
    C_NAME VARCHAR(50), 
    C_EMAIL VARCHAR(50), 
    C_PASSWORD VARCHAR(15), 
    C_ADDRESS VARCHAR(50),
    C_CITY VARCHAR(50),
    C_STATE VARCHAR(50),
    C_ZIPCODE INT (50) ,
    C_CREDITCARD INT (50),
    C_EXPIRY_DATE DATE, 
    C_CVV INT(50),
    C_BILLINGZIP INT(50),
    PRIMARY KEY(ID) 
    
);


INSERT INTO customer_data (C_NAME, C_EMAIL, 
C_PASSWORD, C_ADDRESS, C_CITY, 
C_STATE, C_ZIPCODE, C_CREDITCARD, C_EXPIRY_DATE, 
C_CVV, C_BILLINGZIP)
VALUES ('Craig', 'John@gmail.com', 'secret', 
'123 flower st.', 'Dallas', 'TX', 90898, 34343434, 
'1981-08-24', 432, 90898)